<a href="https://colab.research.google.com/github/sharan11/Intro-to-Deep-Learning-with-Pytorch-Exercise-Solutions/blob/master/Tensors_in_pytorch_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Importing pytorch
import torch

In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [65]:
weights.shape

torch.Size([1, 5])

Exercise: Calculate the output of the network with input features features, weights weights, and bias bias. Similar to Numpy, PyTorch has a torch.sum() function, as well as a .sum() method on tensors, for taking sums. Use the function activation defined above as the activation function.

In [66]:
## Calculate the output of this network using the weights and bias tensors
y = activation(torch.sum(features*weights) + bias)
print(y)

tensor([[0.1595]])


In [67]:
## Calculate the output of this network using matrix multiplication
y = activation(torch.mm(features,weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


### Stack them up!

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

**Exercise:** Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.

In [0]:
h1 = activation(torch.mm(features,W1)+B1)

In [73]:
h1

tensor([[0.6813, 0.4355]])

In [74]:
## Your solution here
output = activation(torch.mm(h1, W2) + B2)
print(output)

tensor([[0.3171]])


### Numpy to Torch and back

In [75]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.66269531, 0.16428823, 0.46074136],
       [0.9048801 , 0.10294873, 0.42955963],
       [0.94890492, 0.52612125, 0.63947146],
       [0.86016393, 0.93815094, 0.65431759]])

In [76]:
b = torch.from_numpy(a)
b

tensor([[0.6627, 0.1643, 0.4607],
        [0.9049, 0.1029, 0.4296],
        [0.9489, 0.5261, 0.6395],
        [0.8602, 0.9382, 0.6543]], dtype=torch.float64)

In [77]:

b.numpy()

array([[0.66269531, 0.16428823, 0.46074136],
       [0.9048801 , 0.10294873, 0.42955963],
       [0.94890492, 0.52612125, 0.63947146],
       [0.86016393, 0.93815094, 0.65431759]])

In [78]:
b.mul_(2)

tensor([[1.3254, 0.3286, 0.9215],
        [1.8098, 0.2059, 0.8591],
        [1.8978, 1.0522, 1.2789],
        [1.7203, 1.8763, 1.3086]], dtype=torch.float64)

In [79]:
a

array([[1.32539062, 0.32857645, 0.92148272],
       [1.80976021, 0.20589745, 0.85911926],
       [1.89780984, 1.05224251, 1.27894293],
       [1.72032786, 1.87630188, 1.30863517]])